// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioApi.Data;

#nullable disable

namespace PortfolioApi.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260129213452_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PortfolioApi.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CtaText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentCompany")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CurrentRole")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EducationDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EducationPeriod")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EducationTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FocusDetail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FocusTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhatIDo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CtaText = "I actively seek opportunities to collaborate with fellow developers, contribute to meaningful projects, and engage in knowledge sharing within the tech community. I'm particularly interested in discussing innovative solutions, software architecture, and the future of technology.",
                            CurrentCompany = "Ithinka IT and IoT Technologies",
                            CurrentRole = "Software Developer",
                            EducationDetail = "Bursa Technical University (2021-2026)",
                            EducationPeriod = "2021-2026",
                            EducationTitle = "Computer Engineering",
                            FocusDetail = "RESTful APIs, Database Optimization",
                            FocusTitle = "Backend Development & Scalable Systems",
                            Intro = "I'm a dedicated software engineer with expertise in modern web technologies and a passion for building scalable, high-performance applications. Currently advancing my proficiency in TypeScript, Redux, and Node.js while exploring emerging technologies including quantum computing.",
                            WhatIDo = "[\"Architecting responsive web applications with React and Angular\",\"Designing and implementing scalable backend systems\",\"Database optimization and API development\",\"Staying current with industry best practices and emerging technologies\"]"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "$2a$11$YY1HXZYxDGCqApXuR9YqeuzBVmw/cRXAoso.a9Y7ce7aTGvPXzCVy",
                            Username = "ardaadmin"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CtaText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IntroText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IntroTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CtaText = "Ready to start a conversation?",
                            Email = "ardaaydinkilinc@gmail.com",
                            IntroText = "I'm always open to discussing new projects, creative ideas, or opportunities to be part of your vision. Whether you have a question or just want to say hi, feel free to reach out!",
                            IntroTitle = "Let's Connect!",
                            Location = "Bursa, Turkey",
                            Phone = "+90 542 117 04 72"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Ithinka IT and IoT Technologies",
                            Description = "Working on IoT and software development projects, contributing to modern web applications.",
                            DisplayOrder = 1,
                            Duration = "3 months",
                            Location = "Türkiye · On-site",
                            Period = "Sep 2025 - Present",
                            Technologies = "JavaScript,Node.js,IoT",
                            Title = "Software Developer",
                            Type = "Internship"
                        },
                        new
                        {
                            Id = 2,
                            Company = "EPİAŞ (Energy Exchange Istanbul)",
                            Description = "Developed enterprise-level applications using Spring Boot and Apache Kafka for energy trading systems.",
                            DisplayOrder = 2,
                            Duration = "2 months",
                            Location = "İstanbul, Türkiye · On-site",
                            Period = "Aug 2025 - Sep 2025",
                            Technologies = "Spring Boot,Apache Kafka,Java",
                            Title = "Software Developer",
                            Type = "Internship"
                        },
                        new
                        {
                            Id = 3,
                            Company = "Uludag Project - Medical Imaging",
                            Description = "Built medical imaging platform with Flask RESTful API and Angular frontend. Implemented Agile methodology in team collaboration.",
                            DisplayOrder = 3,
                            Duration = "1 year",
                            Location = "Bursa, Türkiye · Remote",
                            Period = "Jun 2024 - Jun 2025",
                            Technologies = "Angular,Flask,Python,REST API",
                            Title = "Full-Stack Developer",
                            Type = "Scholarship"
                        },
                        new
                        {
                            Id = 4,
                            Company = "BTU Computer Science Society",
                            Description = "Led a community of 400+ members, organized workshops, seminars, and hackathons. Coordinated technical events and fostered collaboration.",
                            DisplayOrder = 4,
                            Duration = "10 months",
                            Location = "Bursa, Türkiye",
                            Period = "Oct 2024 - Jul 2025",
                            Technologies = "Leadership,Event Management,Community Building",
                            Title = "Community Lead",
                            Type = "Leadership"
                        },
                        new
                        {
                            Id = 5,
                            Company = "BTU Computer Science Society",
                            Description = "Assisted in community management and event organization. Helped grow the community and establish technical programs.",
                            DisplayOrder = 5,
                            Duration = "1 year",
                            Location = "Bursa, Türkiye",
                            Period = "Oct 2023 - Oct 2024",
                            Technologies = "Team Coordination,Event Planning",
                            Title = "Co-Lead",
                            Type = "Leadership"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GithubUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkedinUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Profiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Passionate software engineer specializing in backend development and scalable systems. Building robust applications with modern technologies.",
                            Email = "ardaaydinkilinc@gmail.com",
                            GithubUrl = "https://github.com/adraarda23",
                            LinkedinUrl = "https://www.linkedin.com/in/ardaaydınkılınç/",
                            Name = "Arda Aydın Kılınç",
                            Subtitle = "👋 Hello, I'm",
                            Title = "Backend Developer"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DemoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GithubUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("Technologies")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Full-Stack",
                            Description = "A comprehensive medical imaging platform built with Angular and Flask. Features include image processing, RESTful API integration, and real-time data visualization for medical professionals.",
                            DisplayOrder = 1,
                            Technologies = "Angular,Flask,Python,REST API,TypeScript",
                            Title = "Medical Imaging Platform",
                            Year = "2024-2025"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frontend",
                            Description = "Modern and responsive portfolio website built with React and Framer Motion. Features smooth animations, component-based architecture, and optimized performance.",
                            DisplayOrder = 2,
                            GithubUrl = "https://github.com/adraarda23",
                            Technologies = "React,Framer Motion,CSS3,JavaScript",
                            Title = "React Portfolio Website",
                            Year = "2023"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Backend",
                            Description = "Multi-platform bot for Discord and Telegram that provides daily university cafeteria menus. Automated menu updates and notifications for students.",
                            DisplayOrder = 3,
                            GithubUrl = "https://github.com/adraarda23",
                            Technologies = "Python,Discord API,Telegram API,Web Scraping",
                            Title = "Hafize Ana - University Food Bot",
                            Year = "2022"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Description = "Enterprise-level application for energy trading operations using Spring Boot and Apache Kafka. Implemented real-time data processing and event-driven architecture.",
                            DisplayOrder = 4,
                            Technologies = "Spring Boot,Apache Kafka,Java,Microservices",
                            Title = "Energy Trading System",
                            Year = "2025"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SkillCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillCategoryId");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IconClass = "SiJavascript",
                            Level = 90,
                            Name = "JavaScript",
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IconClass = "SiTypescript",
                            Level = 85,
                            Name = "TypeScript",
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IconClass = "FaPython",
                            Level = 85,
                            Name = "Python",
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            IconClass = "FaJava",
                            Level = 80,
                            Name = "Java",
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            IconClass = "FaDatabase",
                            Level = 85,
                            Name = "SQL",
                            SkillCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 1,
                            IconClass = "FaReact",
                            Level = 90,
                            Name = "React",
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 2,
                            IconClass = "FaAngular",
                            Level = 80,
                            Name = "Angular",
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 3,
                            IconClass = "SiRedux",
                            Level = 75,
                            Name = "Redux",
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 4,
                            IconClass = "HtmlCss",
                            Level = 90,
                            Name = "HTML/CSS",
                            SkillCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            IconClass = "FaNode",
                            Level = 85,
                            Name = "Node.js",
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 2,
                            IconClass = "SiExpress",
                            Level = 85,
                            Name = "Express.js",
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 3,
                            IconClass = "SiFlask",
                            Level = 80,
                            Name = "Flask",
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 4,
                            IconClass = "SiSpringboot",
                            Level = 75,
                            Name = "Spring Boot",
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 5,
                            IconClass = "RestApi",
                            Level = 90,
                            Name = "REST API",
                            SkillCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            DisplayOrder = 1,
                            IconClass = "SiPostgresql",
                            Level = 85,
                            Name = "PostgreSQL",
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 16,
                            DisplayOrder = 2,
                            IconClass = "SiMongodb",
                            Level = 80,
                            Name = "MongoDB",
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 17,
                            DisplayOrder = 3,
                            IconClass = "SiMysql",
                            Level = 80,
                            Name = "MySQL",
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 18,
                            DisplayOrder = 4,
                            IconClass = "FaDatabase",
                            Level = 75,
                            Name = "SQLite",
                            SkillCategoryId = 4
                        },
                        new
                        {
                            Id = 19,
                            DisplayOrder = 1,
                            IconClass = "FaDocker",
                            Level = 80,
                            Name = "Docker",
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 20,
                            DisplayOrder = 2,
                            IconClass = "FaGitAlt",
                            Level = 90,
                            Name = "Git",
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 21,
                            DisplayOrder = 3,
                            IconClass = "FaLinux",
                            Level = 80,
                            Name = "Linux",
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 22,
                            DisplayOrder = 4,
                            IconClass = "SiNginx",
                            Level = 70,
                            Name = "NGINX",
                            SkillCategoryId = 5
                        },
                        new
                        {
                            Id = 23,
                            DisplayOrder = 5,
                            IconClass = "SiApachekafka",
                            Level = 70,
                            Name = "Apache Kafka",
                            SkillCategoryId = 5
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.SkillCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SkillCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Icon = "💻",
                            Title = "Languages"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Icon = "🎨",
                            Title = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Icon = "⚙️",
                            Title = "Backend"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Icon = "🗄️",
                            Title = "Databases"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Icon = "🛠️",
                            Title = "DevOps & Tools"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.SocialLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconClass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SocialLinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#333",
                            DisplayOrder = 1,
                            IconClass = "FaGithub",
                            Name = "GitHub",
                            Url = "https://github.com/adraarda23"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#0077b5",
                            DisplayOrder = 2,
                            IconClass = "FaLinkedin",
                            Name = "LinkedIn",
                            Url = "https://www.linkedin.com/in/ardaaydınkılınç/"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ea4335",
                            DisplayOrder = 3,
                            IconClass = "FaEnvelope",
                            Name = "Email",
                            Url = "mailto:ardaaydinkilinc@gmail.com"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Label = "Years of Experience",
                            Number = "3+"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Label = "Technologies",
                            Number = "10+"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Label = "Projects Completed",
                            Number = "5+"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Label = "Community Members Led",
                            Number = "400+"
                        });
                });

            modelBuilder.Entity("PortfolioApi.Entities.Skill", b =>
                {
                    b.HasOne("PortfolioApi.Entities.SkillCategory", "SkillCategory")
                        .WithMany("Skills")
                        .HasForeignKey("SkillCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkillCategory");
                });

            modelBuilder.Entity("PortfolioApi.Entities.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
